---

handlers:
- name: slack
  config:
    token:
    webhook:
- name: aws_sns
  config:
    access_key:
    access_secret:
    region:
    topic:
- name: email
  config: 
    domain:
    port:
    user:
    pass:
    from:

events:
- name: PROCESS_STATE_EXITED
  handlers:
  - name: slack
    config:
      channel:
  - name: aws_sns
    config:
      topic:
- name: PROCESS_STATE
  handlers:
  - name: email
    config:
      to:
- name: TICK_EVENT
  handlers:
  - name: aws_sns
    config:
      topic:
